import type {
  AnimeWork,
  ExportRecord,
  LedgerEntry,
  LedgerSettings,
} from "./models";

const today = "2026-07-26";

export const demoAnimeWorks: AnimeWork[] = [
  {
    id: "work-rezero",
    title: "Re:Zero",
    subtitle: "Re:ゼロから始める異世界生活",
    aliases: ["Re:从零开始的异世界生活", "从零开始"],
    coverUrl: "/assets/anime-cover-purple.jpg",
    accent: "#8a6fe8",
    watchStatus: "watching",
    statusLabel: "观看中",
    overallScore: 9.6,
    logCount: 14,
    lastLoggedAt: `${today}T08:40:00Z`,
    lastLoggedDatePrecision: "exact",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: `${today}T08:41:12Z`,
    description: "持续记录整季与单集评分，保留每次观看后的原始感想。",
  },
  {
    id: "work-bocchi",
    title: "孤独摇滚！",
    subtitle: "ぼっち・ざ・ろっく！",
    aliases: ["Bocchi the Rock!", "波奇酱"],
    coverUrl: "/assets/anime-cover-pink.jpg",
    accent: "#ee7fa9",
    watchStatus: "completed",
    statusLabel: "已看完",
    overallScore: 9.4,
    logCount: 12,
    lastLoggedAt: "2026-07-24T13:10:00Z",
    lastLoggedDatePrecision: "exact",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-07-24T13:11:05Z",
    description: "对舞台演出、角色细节和喜剧节奏的长期回看记录。",
  },
  {
    id: "work-chiramune",
    title: "弹珠汽水瓶里的千岁同学",
    subtitle: "千歳くんはラムネ瓶のなか",
    aliases: ["千岁同学", "Chiramune"],
    coverUrl: "/assets/anime-cover-amber.png",
    accent: "#e4ad42",
    watchStatus: "watching",
    statusLabel: "观看中",
    overallScore: 8.7,
    logCount: 7,
    lastLoggedAt: "2026-07-23T14:20:00Z",
    lastLoggedDatePrecision: "exact",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-07-23T14:22:09Z",
    description: "人物关系、镜头表达与原作改编节奏的逐集观察。",
  },
  {
    id: "work-frieren",
    title: "葬送的芙莉莲",
    subtitle: "葬送のフリーレン",
    aliases: ["Frieren"],
    coverUrl: "/assets/anime-cover-blue.png",
    accent: "#719fc8",
    watchStatus: "paused",
    statusLabel: "暂停",
    overallScore: 9.2,
    logCount: 9,
    lastLoggedAt: "2026-07-19T12:30:00Z",
    lastLoggedDatePrecision: "exact",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-07-19T12:31:14Z",
    description: "关于时间、记忆与缓慢叙事的私人观看档案。",
  },
  {
    id: "work-euphonium",
    title: "吹响！上低音号",
    subtitle: "響け！ユーフォニアム",
    aliases: ["京吹", "Sound! Euphonium"],
    coverUrl: "/assets/anime-cover-green.png",
    accent: "#5fa889",
    watchStatus: "completed",
    statusLabel: "已看完",
    overallScore: 9.8,
    logCount: 18,
    lastLoggedAt: "2026-07-12T11:00:00Z",
    lastLoggedDatePrecision: "exact",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-07-12T11:00:00Z",
    description: "围绕成长、选择与演奏细节整理的高分作品记录。",
  },
];

export const demoEntries: LedgerEntry[] = [
  {
    id: "entry-rezero-04",
    type: "anime",
    title: "《Re:Zero》第三季 第 4 集",
    bodyRaw:
      "记一下，今天看了《Re:Zero》第三季第 4 集，8.8 分。艾米莉亚这一段挺自然，但整集节奏稍微有点赶。",
    bodySummary: "艾米莉亚的段落自然，整集节奏稍赶。",
    occurredAt: `${today}T08:40:00Z`,
    datePrecision: "exact",
    createdAt: `${today}T08:41:12Z`,
    visibility: "private",
    status: "active",
    sourceChannel: "wechat",
    sourceMessageId: "wx_20260726_0840",
    tags: ["动漫", "单集", "艾米莉亚"],
    score: 8.8,
    mediaWorkId: "work-rezero",
    seasonLabel: "3",
    episodeLabel: "4",
    ratingScope: "episode",
    versionNo: 1,
    media: [],
    followUps: [
      {
        id: "followup-rezero-04",
        body: "隔天又想了一下：节奏赶主要是因为原作这一卷信息量太大，可以理解。",
        sourceChannel: "web",
        createdAt: `${today}T12:05:00Z`,
      },
    ],
    revisions: [
      {
        id: "rev-rezero-01",
        versionNo: 1,
        bodyRaw:
          "记一下，今天看了《Re:Zero》第三季第 4 集，8.8 分。艾米莉亚这一段挺自然，但整集节奏稍微有点赶。",
        reason: "首次写入",
        actor: "Hermes Agent",
        createdAt: `${today}T08:41:12Z`,
      },
    ],
    audit: [
      {
        id: "audit-rezero-01",
        action: "entry.created",
        actor: "Hermes Agent",
        detail: "通过 log_media 创建；默认保持私人。",
        createdAt: `${today}T08:41:12Z`,
      },
    ],
  },
  {
    id: "entry-ledger-idea",
    type: "idea",
    title: "公开接口必须有静态回退",
    bodyRaw:
      "记录：主站远程读取失败时不能空白，动漫页至少保留一个版本周期的本地 JSON 回退。",
    bodySummary: "为主站动漫页保留本地静态数据回退。",
    occurredAt: `${today}T06:20:00Z`,
    datePrecision: "exact",
    createdAt: `${today}T06:20:19Z`,
    visibility: "private",
    status: "active",
    sourceChannel: "wechat",
    sourceMessageId: "wx_20260726_0620",
    tags: ["产品", "降级", "主站"],
    score: null,
    mediaWorkId: null,
    seasonLabel: null,
    episodeLabel: null,
    ratingScope: null,
    versionNo: 2,
    media: [],
    followUps: [],
    revisions: [
      {
        id: "rev-idea-01",
        versionNo: 1,
        bodyRaw: "记录：主站远程读取失败时不能空白。",
        reason: "首次写入",
        actor: "Hermes Agent",
        createdAt: `${today}T06:20:19Z`,
      },
      {
        id: "rev-idea-02",
        versionNo: 2,
        bodyRaw:
          "记录：主站远程读取失败时不能空白，动漫页至少保留一个版本周期的本地 JSON 回退。",
        reason: "补充回退周期",
        actor: "网页管理端",
        createdAt: `${today}T06:28:03Z`,
      },
    ],
    audit: [
      {
        id: "audit-idea-01",
        action: "entry.updated",
        actor: "网页管理端",
        detail: "version 1 → 2；保留原始修订。",
        createdAt: `${today}T06:28:03Z`,
      },
    ],
  },
  {
    id: "entry-bocchi-live",
    type: "anime",
    title: "《孤独摇滚！》第 8 集回看",
    bodyRaw:
      "第 8 集再看还是 9.6 分。演出后的安静比第一次更有力量，公开这条到动漫页。",
    bodySummary: "演出后的安静在回看时更有力量。",
    occurredAt: "2026-07-24T13:10:00Z",
    datePrecision: "exact",
    createdAt: "2026-07-24T13:11:05Z",
    visibility: "public",
    status: "active",
    sourceChannel: "wechat",
    sourceMessageId: "wx_20260724_1310",
    tags: ["动漫", "回看", "公开"],
    score: 9.6,
    mediaWorkId: "work-bocchi",
    seasonLabel: "1",
    episodeLabel: "8",
    ratingScope: "episode",
    versionNo: 2,
    media: [
      {
        id: "media-bocchi-stage",
        kind: "image",
        mimeType: "image/jpeg",
        url: "/assets/anime-ui/bocchi-stage.jpg",
        width: 1760,
        height: 2160,
        durationMs: null,
      },
    ],
    followUps: [],
    revisions: [
      {
        id: "rev-bocchi-01",
        versionNo: 1,
        bodyRaw: "第 8 集再看还是 9.6 分。演出后的安静比第一次更有力量。",
        reason: "首次写入",
        actor: "Hermes Agent",
        createdAt: "2026-07-24T13:11:05Z",
      },
      {
        id: "rev-bocchi-02",
        versionNo: 2,
        bodyRaw:
          "第 8 集再看还是 9.6 分。演出后的安静比第一次更有力量，公开这条到动漫页。",
        reason: "确认公开快照",
        actor: "用户本人",
        createdAt: "2026-07-24T13:14:22Z",
      },
    ],
    audit: [
      {
        id: "audit-bocchi-01",
        action: "entry.published",
        actor: "用户本人",
        detail: "使用确认短码发布到 /public/v1/anime。",
        createdAt: "2026-07-24T13:14:22Z",
      },
    ],
  },
  {
    id: "entry-weekly-mood",
    type: "mood",
    title: "维护负担有点集中",
    bodyRaw:
      "存一下：这周同时维护太多页面时会明显烦躁。先把 Life Ledger 的动漫闭环做完，不扩摄影附件。",
    bodySummary: "维护负担集中；继续收敛动漫 MVP。",
    occurredAt: "2026-07-25T02:05:00Z",
    datePrecision: "exact",
    createdAt: "2026-07-25T02:05:31Z",
    visibility: "private",
    status: "active",
    sourceChannel: "wechat",
    sourceMessageId: "wx_20260725_0205",
    tags: ["自述", "维护负担", "MVP"],
    score: null,
    mediaWorkId: null,
    seasonLabel: null,
    episodeLabel: null,
    ratingScope: null,
    versionNo: 1,
    media: [],
    followUps: [],
    revisions: [
      {
        id: "rev-mood-01",
        versionNo: 1,
        bodyRaw:
          "存一下：这周同时维护太多页面时会明显烦躁。先把 Life Ledger 的动漫闭环做完，不扩摄影附件。",
        reason: "首次写入",
        actor: "Hermes Agent",
        createdAt: "2026-07-25T02:05:31Z",
      },
    ],
    audit: [
      {
        id: "audit-mood-01",
        action: "entry.created",
        actor: "Hermes Agent",
        detail: "self_reported_mood；不生成心理诊断。",
        createdAt: "2026-07-25T02:05:31Z",
      },
    ],
  },
  {
    id: "entry-chiramune-07",
    type: "anime",
    title: "《弹珠汽水瓶里的千岁同学》第 7 集",
    bodyRaw:
      "第 7 集给 8.7。光线和人物距离感做得很好，但后半段转折有一点急。",
    bodySummary: "光线与人物距离感突出，后半段转折略急。",
    occurredAt: "2026-07-23T14:20:00Z",
    datePrecision: "exact",
    createdAt: "2026-07-23T14:22:09Z",
    visibility: "publish_pending",
    status: "active",
    sourceChannel: "web",
    sourceMessageId: null,
    tags: ["动漫", "单集", "待确认"],
    score: 8.7,
    mediaWorkId: "work-chiramune",
    seasonLabel: "1",
    episodeLabel: "7",
    ratingScope: "episode",
    versionNo: 1,
    media: [],
    followUps: [],
    revisions: [
      {
        id: "rev-chiramune-01",
        versionNo: 1,
        bodyRaw:
          "第 7 集给 8.7。光线和人物距离感做得很好，但后半段转折有一点急。",
        reason: "首次写入",
        actor: "网页管理端",
        createdAt: "2026-07-23T14:22:09Z",
      },
    ],
    audit: [
      {
        id: "audit-chiramune-01",
        action: "publish.prepared",
        actor: "用户本人",
        detail: "公开预览已生成，等待文本确认。",
        createdAt: "2026-07-23T14:25:10Z",
      },
    ],
  },
  {
    id: "entry-frieren-note",
    type: "note",
    title: "芙莉莲第 18 集待补感想",
    bodyRaw: "记一下：第 18 集先标记看完，晚点补完整感想。",
    bodySummary: "已看完，感想待补。",
    occurredAt: "2026-07-19T12:30:00Z",
    datePrecision: "exact",
    createdAt: "2026-07-19T12:31:14Z",
    visibility: "private",
    status: "deleted",
    sourceChannel: "wechat",
    sourceMessageId: "wx_20260719_1230",
    tags: ["待补", "动漫"],
    score: null,
    mediaWorkId: "work-frieren",
    seasonLabel: "1",
    episodeLabel: "18",
    ratingScope: "episode",
    versionNo: 1,
    media: [],
    followUps: [],
    revisions: [
      {
        id: "rev-frieren-01",
        versionNo: 1,
        bodyRaw: "记一下：第 18 集先标记看完，晚点补完整感想。",
        reason: "首次写入",
        actor: "Hermes Agent",
        createdAt: "2026-07-19T12:31:14Z",
      },
    ],
    audit: [
      {
        id: "audit-frieren-01",
        action: "entry.deleted",
        actor: "用户本人",
        detail: "软删除；可从回收站恢复。",
        createdAt: "2026-07-19T12:35:30Z",
      },
    ],
  },
];

export const demoExports: ExportRecord[] = [
  {
    id: "export-20260726",
    format: "jsonl",
    scope: "incremental",
    status: "completed",
    createdAt: `${today}T03:20:00Z`,
    completedAt: `${today}T03:20:12Z`,
    size: "42 KB",
    checksum: "sha256:1b4f…9ac2",
    rowCount: 68,
  },
  {
    id: "export-20260720",
    format: "sql",
    scope: "full",
    status: "completed",
    createdAt: "2026-07-20T04:00:00Z",
    completedAt: "2026-07-20T04:00:31Z",
    size: "188 KB",
    checksum: "sha256:92de…813a",
    rowCount: 412,
  },
  {
    id: "export-20260713",
    format: "archive",
    scope: "full",
    status: "completed",
    createdAt: "2026-07-13T04:00:00Z",
    completedAt: "2026-07-13T04:00:44Z",
    size: "201 KB",
    checksum: "sha256:0c71…8fa4",
    rowCount: 387,
  },
];

export const demoSettings: LedgerSettings = {
  timezone: "Asia/Tokyo",
  captureMode: "safe",
  publicPreview: true,
  sensitiveWarning: true,
  weeklyReview: false,
  retentionDaily: 30,
  retentionWeekly: 12,
};
